config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :harvests, except: %i[index destroy]
  resources :offerings do
    member do
      get :print
    end
  end
  resources :locations
  resources :products, except: :destroy
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'pages#home'

  resource :session, only: %i[new create destroy]
  delete 'logout', to: 'sessions#destroy', as: 'logout'
end

app/views/pages/home.html.erb
Oi! Você está na tela inicial do sistema.

<% if policy(User).create? %>
  <p><%= link_to users_path do %>Manage Users<% end %></p>
<% end %>

<% if policy(Location).create? %>
  <p><%= link_to locations_path do %>Manage Locations<% end %></p>
<% end %>

<% if policy(Product).index? %>
  <p><%= link_to products_path do %>Manage Products<% end %></p>
<% end %>

<% if policy(Offering).index? %>
  <p><%= link_to offerings_path do %>Manage Offerings<% end %></p>
<% end %>

<% if policy(Harvest).create? %>
  <p><%= harvest_link(@current_harvest) %></p>
<% end %>

<%= button_to 'Logout', logout_path, method: :delete, data: { confirm: 'Are you sure you want to log out?' } %>